# Generated by Django 3.1.14 on 2022-03-17 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isArchieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ChatingPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformName', models.CharField(default='Open World', max_length=50)),
                ('platformNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(default='Open World', max_length=50)),
                ('numberOfTimeSelected', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FakeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=300)),
                ('isProfileReadyToUse', models.BooleanField(default=False)),
                ('selectedCollege', models.CharField(blank=True, default='', max_length=20)),
                ('profilePicture', models.ImageField(default='images/logo.png', upload_to='profilePicture')),
                ('isOnline', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isArchieved', models.BooleanField(default=False)),
                ('chatBoxes', models.ManyToManyField(blank=True, to='core.ChatBox')),
                ('chatingPlatform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.chatingplatform')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chater', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isArchieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(default='', max_length=12)),
                ('isEmailVerified', models.BooleanField(default=False)),
                ('isEmailNotificationAllowed', models.BooleanField(default=True)),
                ('tempPassword', models.CharField(default='12345678', max_length=50)),
                ('fakeProfiles', models.ManyToManyField(blank=True, to='core.FakeProfile')),
                ('selectedColleges', models.ManyToManyField(blank=True, to='core.College')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatbox',
            name='chaters',
            field=models.ManyToManyField(blank=True, to='core.Chater'),
        ),
        migrations.AddField(
            model_name='chatbox',
            name='messages',
            field=models.ManyToManyField(blank=True, to='core.Message'),
        ),
    ]
