# Generated by Django 3.1.14 on 2022-03-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='collegeName',
            field=models.CharField(default='Open World', max_length=500),
        ),
        migrations.AlterField(
            model_name='fakeprofile',
            name='displayName',
            field=models.CharField(default='Unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='fakeprofile',
            name='isOnline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fakeprofile',
            name='selectedCollege',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
