# Generated by Django 3.1.14 on 2022-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220318_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSellerEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=354)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('isAllowed', models.BooleanField(default=True)),
            ],
        ),
    ]
